version: "3"
services:
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: ogDTnx7oA4gF1odp
      POSTGRES_DB: pgvector

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - ./.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # The uploadservice is now part of the frontend, so we don't need a separate service for it

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data: