name: Deploy to Azure Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Add startup script for system dependencies
      - name: Create startup script
        working-directory: ./backend
        run: |
          echo "#!/bin/bash" > startup.sh
          echo "apt-get update" >> startup.sh
          echo "apt-get install -y libgl1-mesa-glx libglib2.0-0" >> startup.sh
          echo "python -m uvicorn app:app --host 0.0.0.0 --port 8000" >> startup.sh
          chmod +x startup.sh
      
      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt
        
      - name: List backend directory contents
        run: |
          echo "Backend directory contents:"
          ls -R backend/

      - name: Zip artifact for deployment
        run: |
          cd backend
          zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            backend/release.zip
            !venv/

      - name: Download artifact for deployment
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'jscbbackend01'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          clean: true